namespace: node-tainter
resources:
- 00-namespace.yaml
- daemonset.yaml
- scripts-configmap.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/takutakahashi/node-tainter
  newTag: beta